# Generated by Django 2.2 on 2020-04-24 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeningGame', '0003_auto_20200319_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeninggamedata',
            name='adjustTimings',
        ),
        migrations.RemoveField(
            model_name='listeninggamedata',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='listeninggamedata',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='listeninggamedata',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='listeninggamedata',
            name='pauseTimeEnd',
        ),
        migrations.RemoveField(
            model_name='listeninggamedata',
            name='pauseTimeStart',
        ),
        migrations.RemoveField(
            model_name='listeninggamedata',
            name='startTime',
        ),
        migrations.AddField(
            model_name='listeninggamedata',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='000', max_length=100), default=list, size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='listeninggamedata',
            name='audioAdjust',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='000', max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='listeninggamedata',
            name='audioEnd',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='000', max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='listeninggamedata',
            name='audioPause',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='000', max_length=100), default=list, size=None),
        ),
        migrations.AddField(
            model_name='listeninggamedata',
            name='audioStart',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='000', max_length=100), default=list, size=None),
        ),
    ]
