# Generated by Django 2.2 on 2020-03-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionPredictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotionpredictordata',
            old_name='uid',
            new_name='email',
        ),
    ]
