# Generated by Django 2.2 on 2020-04-24 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotionPredictor', '0003_auto_20200319_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionpredictordata',
            name='timeChosen',
        ),
        migrations.AlterField(
            model_name='emotionpredictordata',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='000', max_length=100), default=list, size=None), default=list, size=None),
        ),
    ]
