# Generated by Django 2.2 on 2020-04-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotionPredictor', '0004_auto_20200424_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionpredictordata',
            name='answers',
        ),
    ]
