# Generated by Django 2.2 on 2020-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnMax', '0002_auto_20200319_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnmaxdata',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
