# Generated by Django 2.2 on 2020-03-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earnMax', '0003_auto_20200319_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnmaxdata',
            old_name='email',
            new_name='email_id',
        ),
    ]
