# Generated by Django 2.2 on 2020-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnMax', '0004_auto_20200319_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earnmaxdata',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='earnmaxdata',
            name='id',
        ),
        migrations.AddField(
            model_name='earnmaxdata',
            name='emailId',
            field=models.EmailField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
