# Generated by Django 2.2 on 2020-03-20 06:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloonGame', '0003_auto_20200319_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloongamedata',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='balloongamedata',
            name='clicks',
        ),
        migrations.AddField(
            model_name='balloongamedata',
            name='amountCollected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='balloongamedata',
            name='clicksBursted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='balloongamedata',
            name='clicksCollected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
