# Generated by Django 2.2 on 2020-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('teachingExp', models.IntegerField()),
                ('teachingField', models.IntegerField()),
            ],
        ),
    ]
