# Generated by Django 2.2 on 2020-03-19 08:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20200318_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='uid',
        ),
        migrations.AddField(
            model_name='userdata',
            name='games_played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='userdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=False, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='teachingExp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='teachingField',
            field=models.IntegerField(default=0),
        ),
    ]
