# Generated by Django 2.2 on 2020-03-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_auto_20200319_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
