# Generated by Django 2.2 on 2020-04-23 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_auto_20200319_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='games_played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=list, size=None),
        ),
    ]
